sonar.projectKey=grigoriev_sb-ctrl-ui
sonar.organization=grigoriev

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=dist/**,node_modules/**,src/main.tsx,src/vite-env.d.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,src/test/**,src/main.tsx
